
 angular.module('myApp.products')
     .service("productsService", function(){
            this.getAll = function(){
                return [
                    {id : 1, name : "Pen", cost : 5, units : 100, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam non vitae vero quasi fuga eius illum, at. Quasi provident expedita, voluptatem illum dolorem exercitationem, sapiente atque nulla, aperiam nihil sit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet culpa sed vero assumenda molestias, quis ullam! Unde omnis, rem soluta neque laudantium vitae possimus temporibus. Architecto ea laborum velit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium autem aut, nobis perspiciatis molestias atque voluptatem maxime numquam, dolorum libero reiciendis aperiam placeat tempore quis debitis. Possimus eveniet, explicabo inventore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi iure consequuntur debitis labore vero, nihil neque, ea totam assumenda iusto ullam voluptatibus aperiam aut maiores impedit facilis! Sed, porro, officiis?"},
                    {id : 2, name : "Hen", cost : 90, units : 200, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam non vitae vero quasi fuga eius illum, at. Quasi provident expedita, voluptatem illum dolorem exercitationem, sapiente atque nulla, aperiam nihil sit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet culpa sed vero assumenda molestias, quis ullam! Unde omnis, rem soluta neque laudantium vitae possimus temporibus. Architecto ea laborum velit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium autem aut, nobis perspiciatis molestias atque voluptatem maxime numquam, dolorum libero reiciendis aperiam placeat tempore quis debitis. Possimus eveniet, explicabo inventore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi iure consequuntur debitis labore vero, nihil neque, ea totam assumenda iusto ullam voluptatibus aperiam aut maiores impedit facilis! Sed, porro, officiis?"},
                    {id : 3, name : "Ten", cost : 10, units : 10, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam non vitae vero quasi fuga eius illum, at. Quasi provident expedita, voluptatem illum dolorem exercitationem, sapiente atque nulla, aperiam nihil sit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet culpa sed vero assumenda molestias, quis ullam! Unde omnis, rem soluta neque laudantium vitae possimus temporibus. Architecto ea laborum velit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium autem aut, nobis perspiciatis molestias atque voluptatem maxime numquam, dolorum libero reiciendis aperiam placeat tempore quis debitis. Possimus eveniet, explicabo inventore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi iure consequuntur debitis labore vero, nihil neque, ea totam assumenda iusto ullam voluptatibus aperiam aut maiores impedit facilis! Sed, porro, officiis?"},
                    {id : 4, name : "Den", cost : 100, units : 1, desc : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam non vitae vero quasi fuga eius illum, at. Quasi provident expedita, voluptatem illum dolorem exercitationem, sapiente atque nulla, aperiam nihil sit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet culpa sed vero assumenda molestias, quis ullam! Unde omnis, rem soluta neque laudantium vitae possimus temporibus. Architecto ea laborum velit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium autem aut, nobis perspiciatis molestias atque voluptatem maxime numquam, dolorum libero reiciendis aperiam placeat tempore quis debitis. Possimus eveniet, explicabo inventore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi iure consequuntur debitis labore vero, nihil neque, ea totam assumenda iusto ullam voluptatibus aperiam aut maiores impedit facilis! Sed, porro, officiis?"}
                ]
            }
            this.get = function(id){
                return this.getAll().filter(function(data){
                    return data.id === id;
                })[0];
            }
        });
